import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    java
    `maven-publish`
    kotlin("jvm") version "1.4.30"
}

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor(project(":annotationProcessor"))
    implementation(project(":annotationProcessor"))
    testImplementation(project(":annotationProcessor"))
    implementation(project(":annotation"))
    implementation("io.github.classgraph:classgraph:4.8.102")
    implementation("org.scijava:parsington:2.0.0")
    implementation("org.bushe:eventbus:1.4")
    implementation("javax.xml.bind:jaxb-api:2.3.1")
    implementation("javax.xml.ws:jaxws-api:2.3.1")
    testImplementation("junit:junit:4.13")
    testImplementation("org.mockito:mockito-core:2.19.0")
    implementation(kotlin("stdlib-jdk8"))
}

group = "org.scijava"
version = "2.86.1-SNAPSHOT"
description = "SciJava Common"
//sourceCompatibility = "1.8"

//configurations.all {
//}
//
//
//
//java {
//    println "Classpath = ${sourceSets.main.compileClasspath.asPath}";
//    withSourcesJar()
//}
//
//publishing {
//    publications {
//        maven(MavenPublication) {
//            from(components.java)
//        }
//    }
//}
//
//tasks.withType(JavaCompile) {
//    options.encoding = "UTF-8"
//}



tasks {
    withType<KotlinCompile> { kotlinOptions.jvmTarget = "1.8" }

//    compileJava {
//        options.annotationProcessorPath = configurations.annotationProcessor.get()
//    }
    withType<JavaCompile> {
        doFirst {
            println("AnnotationProcessorPath for $name is ${options.annotationProcessorPath?.files}")
        }
    }
}